language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "Xrtr/03puOY9Kd1pYpS8fPcnNPDJ3BqQ+sn+seq9WMz/V55+bHEWDmPrZp3Mi3UHnlXLccsJnRD+AZpY4bN1FBeDHL184Zhu3PgKFrvzDk4Fh/NDo8yexArN543EG4nvM1kCE921WP+GGLMfUOAb/ULyRnTaLlCvbcv2oAJcXsY="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/grunt-niteo-spawn

