language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '4.1'
before_script:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: g+bf9U/quLC9RTG6C6oaArRI/jyOz+HP1ZZQ6gMaQLeV35l2xeD9rFiXNJ3yhsWLGrJCDnpHxBcm/OdDlzXd18oP+HkAEOtbQPdqmKeVtnxn7dbIRv8TrURZpilFY0GhdJCYVQDI9d/OT+bp281SBnrZyAkAs2HD5RMkUxCA6ys=
  on:
    all_branches: true
    tags: true
    repo: VeriShip/grunt-niteo-spawn
    node: '4.1'
